import type { Puzzle } from "./types";

export const FALLBACK_PUZZLES: Puzzle[] = [
  { start: "Pizza", target: "Egypte antique" },
  { start: "Michael Jackson", target: "Mont Everest" },
  { start: "Echecs", target: "Amazonie" },
  { start: "Titanic (film)", target: "Trou noir" },
  { start: "Football", target: "William Shakespeare" },
  { start: "Harry Potter", target: "Grande Muraille de Chine" },
  { start: "Albert Einstein", target: "Jazz" },
  { start: "Tour Eiffel", target: "Genetique" },
  { start: "Leonard de Vinci", target: "Eruption volcanique" },
  { start: "The Beatles", target: "Bouddhisme" },
  { start: "Dinosaure", target: "Internet" },
  { start: "Napoleon Ier", target: "Musique de jazz" },
  { start: "Cleopatre", target: "Exploration spatiale" },
  { start: "Wolfgang Amadeus Mozart", target: "Foret tropicale" },
  { start: "Isaac Newton", target: "Arts martiaux" },
  { start: "Charles Darwin", target: "Jeux olympiques" },
  { start: "Marie Curie", target: "Hip-hop" },
  { start: "Abraham Lincoln", target: "Recif corallien" },
  { start: "Ludwig van Beethoven", target: "Photographie" },
  { start: "Vincent van Gogh", target: "Tectonique des plaques" },
  { start: "Galilee", target: "Folklore" },
  { start: "Nikola Tesla", target: "Yoga" },
  { start: "Aristote", target: "Television" },
  { start: "Platon", target: "Cinema" },
  { start: "Karl Marx", target: "Surf" },
  { start: "Sigmund Freud", target: "Architecture" },
  { start: "Mahatma Gandhi", target: "Antarctique" },
  { start: "Nelson Mandela", target: "Jazz" },
  { start: "Che Guevara", target: "Sushi" },
  { start: "Barack Obama", target: "Musique classique" },
  { start: "Steve Jobs", target: "Foret amazonienne" },
  { start: "Elon Musk", target: "Dinosaure" },
  { start: "Beyonce", target: "Empire romain" },
  { start: "Taylor Swift", target: "Vikings" },
  { start: "Eminem", target: "Route de la soie" },
  { start: "Bob Dylan", target: "Samurai" },
  { start: "Freddie Mercury", target: "Fleuve Amazone" },
  { start: "David Bowie", target: "Bouddhisme" },
  { start: "Elvis Presley", target: "Mont Fuji" },
  { start: "John Lennon", target: "Trou noir" },
  { start: "Led Zeppelin", target: "Ocean" },
  { start: "Pink Floyd", target: "Democratie" },
  { start: "Nirvana (groupe)", target: "Azteques" },
  { start: "Michel-Ange", target: "Recif corallien" },
  { start: "Raphael (peintre)", target: "Rome antique" },
  { start: "Pablo Picasso", target: "Mythologie nordique" },
  { start: "Frida Kahlo", target: "Age viking" },
  { start: "Salvador Dali", target: "Mecanique quantique" },
  { start: "Andy Warhol", target: "Grande Barriere de corail" },
  { start: "Bruce Lee", target: "Mythologie grecque" },
  { start: "Muhammad Ali", target: "Route de la soie" },
  { start: "Usain Bolt", target: "Revolution francaise" },
  { start: "Serena Williams", target: "Chine antique" },
  { start: "France", target: "Japon" },
  { start: "Paris", target: "Astronomie" },
  { start: "Renaissance", target: "Biologie" },
  { start: "Philosophie", target: "Geographie" },
  { start: "Mathematiques", target: "Musique" },
  { start: "Physique", target: "Litterature" },
  { start: "Chimie", target: "Histoire" },
];

export function getFallbackPuzzle(): Puzzle {
  return FALLBACK_PUZZLES[Math.floor(Math.random() * FALLBACK_PUZZLES.length)];
}
